//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleImages = new HashSet<ArticleImage>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string TitleURL { get; set; }
        public string ContentText { get; set; }
        public byte[] ContentFile { get; set; }
        public string ContentFileURL { get; set; }
        public Nullable<System.Guid> ArticleTypeId { get; set; }
        public string Tags { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleImage> ArticleImages { get; set; }
    }
}
