//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleImage
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ArticleId { get; set; }
        public byte[] Image { get; set; }
        public string ImageURL { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
