//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechPortalEntities : DbContext
    {
        public TechPortalEntities()
            : base("name=TechPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidateEnquiry> CandidateEnquiries { get; set; }
        public virtual DbSet<Skillset> Skillsets { get; set; }
        public virtual DbSet<CandidateEnquiryFollowup> CandidateEnquiryFollowups { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleType> ArticleTypes { get; set; }
        public virtual DbSet<ArticleImage> ArticleImages { get; set; }
    }
}
